server:
  port: 9001

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  cloud:
    config:
      import-check:
        enabled: false
  zipkin:
    base-url: http://127.0.0.1:9411/

logging:
  file:
    path: C:\