server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer-service
                fallbackuri: forward:/customerServiceFallBack
        - id : NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: NOTIFICATION-SERVICE
                fallbackuri: forward:/notificationServiceFallback
      filter:
        circuit-breaker:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
    config:
      import-check:
        enabled: false



